apiVersion: apps/v1
kind: Deployment
metadata:
  name: burger-app-backend
  namespace: project3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burger-app-backend
  template:
    metadata:
      labels:
        app: burger-app-backend
    spec:
      containers:
      - image: khalidharbi/test-back-project2:latest
        name: burger-app-backend
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dbconfig
        - secretRef:
            name: my-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
